apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: austinsky/hipster-frontend:v0.0.1
    name: frontend
    resources: {}
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "vasya"
    - name: CURRENCY_SERVICE_ADDR
      value: "petya"

    - name: CART_SERVICE_ADDR
      value: "vanya"
    
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "zhenya"
    
    - name: SHIPPING_SERVICE_ADDR
      value: "vasya"
   
    - name: CHECKOUT_SERVICE_ADDR
      value: "check"
    
    - name: AD_SERVICE_ADDR
      value: "ImenaConchilis"
    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# - name: PORT
#   value: "8080"
# value: "productcatalogservice:3550"
# value: "currencyservice:7000"
#   value: "adservice:9555"
#   value: "checkoutservice:5050"
#   value: "shippingservice:50051"
#   value: "recommendationservice:8080"
#   value: "cartservice:7070"